name: project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - openpyxl
  - jupyter
  - jupyter_contrib_nbextensions
  - voila
  - rise
  - scikit-learn
  - altair
  - vega_datasets
  - matplotlib
  - seaborn
  - statsmodels